ERROR_CODES = {
    'NO_RECORD_TO_SAVE': 'ds0',
    'ERR_WHILE_PARSING_DETAILS': 'pp0',
    'CONNECTION_ERROR': 'cn0',
    'TIMEOUT_ERROR': 'to0',
    'ELEMENT_NOT_FOUND': 'enf0',
    'UNKNOWN_ERROR': 'ue0',
}
